In [2]:
import numpy as np
import cv2
import pandas as pd
from torch_snippets import read, show

In [4]:
read('130625_1_001.png').shape

(1080, 1920, 3)

In [ ]:
def int_list(lst):
    # переделывает список списков [[306.00482 190.75961]
                                # [318.99518 183.25961]
                                # [333.99518 209.24039]
                                # [321.00482 216.74039]]
#  в массив array с целыми числами
    a = []
    # b = []
    for i in lst:
        c = []
        for j in i:
            c.append(int(j))
        a.append([c])
    return np.array(a)


img = cv2.imread('pole.jpg')
rot_rectangle = ((320, 200), (30, 15), 60)
box = cv2.boxPoints(rot_rectangle)
print(box)
box = int_list(box)
print(box)
# box = np.int(box) #Convert into integer values
rectangle = cv2.drawContours(img,[box],0,(0,0,255),2)
# cv2.drawContours(img, [100,100,200,200], -1, (0,255,0), 3)
cv2.imshow('Contours', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[306.00482 190.75961]
 [318.99518 183.25961]
 [333.99518 209.24039]
 [321.00482 216.74039]]
[[[306 190]]

 [[318 183]]

 [[333 209]]

 [[321 216]]]
